// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  site: 'https://mirusu400.github.io',
  base: '/wipi-wiki',
  trailingSlash: 'ignore',
  integrations: [
    starlight({
      title: 'WIPI Wiki',
      components: {
        Header: './src/components/Header.astro',
        Sidebar: './src/components/Sidebar.astro',
      },
      description: 'WIPI 모바일 표준 플랫폼 API 레퍼런스',
      defaultLocale: 'root',
      locales: {
        root: { label: '한국어', lang: 'ko' },
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/mirusu400/wipi-wiki',
        },
      ],
      editLink: {
        baseUrl: 'https://github.com/mirusu400/wipi-wiki/edit/main/',
      },
      sidebar: [
        {
          label: '개요',
          items: [
            { label: '소개', link: '/overview/' },
            { label: '1. 서론', link: '/overview/introduction/' },
            { label: '2. 개념적 구조', link: '/overview/architecture/' },
            { label: '3. 주요 기능 규격', link: '/overview/platform/' },
          ],
        },
        {
          label: 'HAL 규격',
          items: [
            { label: 'HAL 개요', link: '/hal/' },
            { label: '4.1 Type Definition', link: '/hal/types/' },
            { label: '4.2 플랫폼 API', link: '/hal/platform-api/' },
            { label: '4.3 System', link: '/hal/system/' },
            { label: '4.4 CALL', link: '/hal/call/' },
            { label: '4.5 HandSet Device', link: '/hal/handset/' },
            { label: '4.6 네트워크', link: '/hal/network/' },
            { label: '4.7 Serial', link: '/hal/serial/' },
            { label: '4.8 MEDIA', link: '/hal/media/' },
            { label: '4.9 TIME', link: '/hal/time/' },
            { label: '4.10 UTILITY', link: '/hal/utility/' },
            { label: '4.11 FILE', link: '/hal/file/' },
            { label: '4.12 InputMethod', link: '/hal/input-method/' },
            { label: '4.13 Font', link: '/hal/font/' },
            { label: '4.14 Frame Buffer', link: '/hal/frame-buffer/' },
            { label: '4.15 Virtual Key', link: '/hal/virtual-key/' },
          ],
        },
        {
          label: 'C API',
          items: [
            { label: 'C API 개요', link: '/c-api/' },
            { label: '5.1.1 커널', link: '/c-api/kernel/' },
            { label: '5.1.2 그래픽', link: '/c-api/graphics/' },
            { label: '5.1.3 데이터베이스', link: '/c-api/database/' },
            { label: '5.1.4 파일시스템', link: '/c-api/filesystem/' },
            { label: '5.1.5 NETWORK', link: '/c-api/network/' },
            { label: '5.1.6 매체 처리기', link: '/c-api/media/' },
            { label: '5.1.7 SERIAL', link: '/c-api/serial/' },
            { label: '5.1.8 PHONE', link: '/c-api/phone/' },
            { label: '5.1.9 MISC', link: '/c-api/misc/' },
            { label: '5.1.10 UTILITY', link: '/c-api/utility/' },
            { label: '5.1.11 UI Components', link: '/c-api/ui-components/' },
            { label: '5.1.12 표준 C 라이브러리', link: '/c-api/c-stdlib/' },
          ],
        },
        {
          label: 'Java API',
          collapsed: true,
          items: [{ autogenerate: { directory: 'java-api' } }],
        },
        {
          label: 'CLDC 1.1',
          items: [
            { label: 'CLDC 개요', link: '/cldc/' },
            { label: '규격서', link: '/cldc/spec/' },
            { label: '바이트 코드 검사기', link: '/cldc/verifier/' },
            { label: 'Java API', link: '/cldc/java-api/' },
          ],
        },
        {
          label: 'CLDC Java API',
          collapsed: true,
          items: [{ autogenerate: { directory: 'cldc/java-api' } }],
        },
        {
          label: 'MIDP 2.0',
          items: [
            { label: 'MIDP 개요', link: '/midp/' },
            { label: '개요 문서', link: '/midp/overview/' },
            { label: 'OTA 규격', link: '/midp/ota-spec/' },
            { label: '보안 정책 (GSM/UMTS)', link: '/midp/security-gsm/' },
            { label: '보안 정책 (RP)', link: '/midp/security-rp/' },
            { label: '라이선스', link: '/midp/license/' },
            { label: 'Java API', link: '/midp/java-api/' },
          ],
        },
        {
          label: 'MIDP Java API',
          collapsed: true,
          items: [{ autogenerate: { directory: 'midp/java-api' } }],
        },
        {
          label: '부속서',
          items: [
            { label: '부속서 개요', link: '/appendix/' },
            { label: '6. 참조 문헌', link: '/appendix/references/' },
            { label: '7.1 EUC-KR 확장', link: '/appendix/euc-kr-extended/' },
            { label: '7.2 API 추가/삭제', link: '/appendix/api-management/' },
            { label: '7.3 보안 관련 API', link: '/appendix/security/' },
            { label: '7.4 Media 관련 API', link: '/appendix/media-ext/' },
          ],
        },
        // ── WIPI 2.0 ──
        {
          label: '개요',
          collapsed: true,
          items: [
            { label: 'WIPI 2.0 소개', link: '/v20/' },
            { label: '1. 서론', link: '/v20/overview/introduction/' },
            { label: '2. 개념적 구조', link: '/v20/overview/architecture/' },
            { label: '3. 주요 기능 규격', link: '/v20/overview/platform/' },
            { label: '4. 참조문헌', link: '/v20/overview/references/' },
          ],
        },
        {
          label: 'HAL 규격',
          collapsed: true,
          items: [
            { label: 'HAL 개요', link: '/v20/hal/' },
            { label: '2.1 변수 타입', link: '/v20/hal/types/' },
            { label: '2.2 플랫폼 API', link: '/v20/hal/platform-api/' },
            { label: '2.3 시스템', link: '/v20/hal/system/' },
            { label: '2.4 타이머', link: '/v20/hal/timer/' },
            { label: '2.5 유니코드', link: '/v20/hal/unicode/' },
            { label: '2.6 폰트', link: '/v20/hal/font/' },
            { label: '2.7 문자 입력 처리', link: '/v20/hal/input-method/' },
            { label: '2.8 가상 키', link: '/v20/hal/virtual-key/' },
            { label: '2.9 Generic I/O', link: '/v20/hal/generic-io/' },
            { label: '2.10 단말 리소스', link: '/v20/hal/terminal-resource/' },
            { label: '2.11 전화걸기', link: '/v20/hal/call/' },
            { label: '2.12 핸드셋 디바이스', link: '/v20/hal/handset/' },
            { label: '2.13 LCD 화면 제어', link: '/v20/hal/lcd/' },
            { label: '2.14 파일', link: '/v20/hal/file/' },
            { label: '2.15 네트워크', link: '/v20/hal/network/' },
            { label: '2.16 시리얼 통신', link: '/v20/hal/serial/' },
            { label: '2.17 매체 처리기', link: '/v20/hal/media/' },
            { label: '2.18 SMS', link: '/v20/hal/sms/' },
            { label: '2.19 위치정보', link: '/v20/hal/location/' },
          ],
        },
        {
          label: 'C API',
          collapsed: true,
          items: [
            { label: 'C API 개요', link: '/v20/c-api/' },
            { label: '2.1 커널', link: '/v20/c-api/kernel/' },
            { label: '2.2 그래픽', link: '/v20/c-api/graphics/' },
            { label: '2.3 파일', link: '/v20/c-api/filesystem/' },
            { label: '2.4 데이터베이스', link: '/v20/c-api/database/' },
            { label: '2.5 네트워크', link: '/v20/c-api/network/' },
            { label: '2.6 시리얼 통신', link: '/v20/c-api/serial/' },
            { label: '2.7 UI 컴포넌트', link: '/v20/c-api/ui-components/' },
            { label: '2.8 유틸리티', link: '/v20/c-api/utility/' },
            { label: '2.9 Generic I/O', link: '/v20/c-api/generic-io/' },
            { label: '2.10 단말 리소스', link: '/v20/c-api/terminal-resource/' },
            { label: '2.11 매체 처리기', link: '/v20/c-api/media/' },
            { label: '2.12 전화걸기', link: '/v20/c-api/phone/' },
            { label: '2.13 SMS', link: '/v20/c-api/sms/' },
            { label: '2.14 위치정보', link: '/v20/c-api/location/' },
            { label: '2.15 보안통신', link: '/v20/c-api/security/' },
            { label: '2.16 부가 장치 제어', link: '/v20/c-api/device-control/' },
            { label: '2.17 수학 연산', link: '/v20/c-api/math/' },
            { label: '3. 표준 C 라이브러리', link: '/v20/c-api/c-stdlib/' },
          ],
        },
        {
          label: 'Java API',
          collapsed: true,
          items: [
            { label: 'Java API 개요', link: '/v20/java-api/' },
            { label: '2.2.1 커널', link: '/v20/java-api/kernel/' },
            { label: '2.2.2 저수준 입출력', link: '/v20/java-api/low-level-io/' },
            { label: '3.1.1 그래픽', link: '/v20/java-api/graphics/' },
            { label: '3.1.2 파일', link: '/v20/java-api/file/' },
            { label: '3.1.3 데이터베이스', link: '/v20/java-api/database/' },
            { label: '3.1.4 고수준 UI', link: '/v20/java-api/ui/' },
            { label: '3.1.5 Generic I/O', link: '/v20/java-api/generic-io/' },
            { label: '3.1.6 단말 리소스', link: '/v20/java-api/terminal-resource/' },
            { label: '3.1.7 주소록', link: '/v20/java-api/addressbook/' },
            { label: '3.1.8 매체 처리기', link: '/v20/java-api/media/' },
            { label: '3.1.9 SMS', link: '/v20/java-api/sms/' },
            { label: '3.1.10 위치 정보', link: '/v20/java-api/location/' },
            { label: '3.1.11 부가 장치 제어', link: '/v20/java-api/device-control/' },
            { label: '4.1 확장 유니코드', link: '/v20/java-api/unicode/' },
          ],
        },
        {
          label: '선택 규격',
          collapsed: true,
          items: [
            { label: '선택 규격 개요', link: '/v20/optional/' },
            { label: '1. 동적 API', link: '/v20/optional/dynamic-api/' },
            { label: '2. VGI 관련 API', link: '/v20/optional/vgi/' },
          ],
        },
        {
          label: '부속서',
          collapsed: true,
          items: [
            { label: '부속서 개요', link: '/v20/appendix/' },
            { label: '1. API 혼용 기준', link: '/v20/appendix/api-interop/' },
            { label: '2. 보안 정책', link: '/v20/appendix/security-policy/' },
            { label: '3. ERROR 반환 값', link: '/v20/appendix/error-codes/' },
            { label: '4. 사용 예제', link: '/v20/appendix/examples/' },
          ],
        },
        // ── WIPI 2.2.0 ──
        {
          label: '개요',
          collapsed: true,
          items: [
            { label: 'WIPI 2.2.0 소개', link: '/v22/' },
            { label: '1. 서론', link: '/v22/overview/introduction/' },
            { label: '2. 개념적 구조', link: '/v22/overview/architecture/' },
            { label: '3. 주요 기능 규격', link: '/v22/overview/platform/' },
            { label: '4. 참조문헌', link: '/v22/overview/references/' },
          ],
        },
        {
          label: 'HAL 규격',
          collapsed: true,
          items: [
            { label: 'HAL 개요', link: '/v22/hal/' },
            { label: '2.1 변수 타입', link: '/v22/hal/types/' },
            { label: '2.2 플랫폼 API', link: '/v22/hal/platform-api/' },
            { label: '2.3 시스템', link: '/v22/hal/system/' },
            { label: '2.4 타이머', link: '/v22/hal/timer/' },
            { label: '2.5 유니코드', link: '/v22/hal/unicode/' },
            { label: '2.6 폰트', link: '/v22/hal/font/' },
            { label: '2.7 문자 입력 처리', link: '/v22/hal/input-method/' },
            { label: '2.8 가상 키', link: '/v22/hal/virtual-key/' },
            { label: '2.9 Generic I/O', link: '/v22/hal/generic-io/' },
            { label: '2.10 단말 리소스', link: '/v22/hal/terminal-resource/' },
            { label: '2.11 전화걸기', link: '/v22/hal/call/' },
            { label: '2.12 핸드셋 디바이스', link: '/v22/hal/handset/' },
            { label: '2.13 LCD 화면 제어', link: '/v22/hal/lcd/' },
            { label: '2.14 파일', link: '/v22/hal/file/' },
            { label: '2.15 네트워크', link: '/v22/hal/network/' },
            { label: '2.16 시리얼 통신', link: '/v22/hal/serial/' },
            { label: '2.17 매체 처리기', link: '/v22/hal/media/' },
            { label: '2.18 SMS', link: '/v22/hal/sms/' },
          ],
        },
        {
          label: 'C API',
          collapsed: true,
          items: [
            { label: 'C API 개요', link: '/v22/c-api/' },
            { label: '2.1 커널', link: '/v22/c-api/kernel/' },
            { label: '2.2 그래픽', link: '/v22/c-api/graphics/' },
            { label: '2.3 파일', link: '/v22/c-api/filesystem/' },
            { label: '2.4 데이터베이스', link: '/v22/c-api/database/' },
            { label: '2.5 네트워크', link: '/v22/c-api/network/' },
            { label: '2.6 시리얼 통신', link: '/v22/c-api/serial/' },
            { label: '2.7 UI 컴포넌트', link: '/v22/c-api/ui-components/' },
            { label: '2.8 유틸리티', link: '/v22/c-api/utility/' },
            { label: '2.9 Generic I/O', link: '/v22/c-api/generic-io/' },
            { label: '2.10 단말 리소스', link: '/v22/c-api/terminal-resource/' },
            { label: '2.11 매체 처리기', link: '/v22/c-api/media/' },
            { label: '2.12 전화걸기', link: '/v22/c-api/phone/' },
            { label: '2.13 SMS', link: '/v22/c-api/sms/' },
            { label: '2.14 보안통신', link: '/v22/c-api/security/' },
            { label: '2.15 부가 장치 제어', link: '/v22/c-api/device-control/' },
            { label: '2.16 수학 연산', link: '/v22/c-api/math/' },
            { label: '3. 표준 C 라이브러리', link: '/v22/c-api/c-stdlib/' },
          ],
        },
        {
          label: 'Java API',
          collapsed: true,
          items: [
            { label: 'Java API 개요', link: '/v22/java-api/' },
            { label: '2.2.1 커널', link: '/v22/java-api/kernel/' },
            { label: '2.2.2 저수준 입출력', link: '/v22/java-api/low-level-io/' },
            { label: '3.1.1 그래픽', link: '/v22/java-api/graphics/' },
            { label: '3.1.2 파일', link: '/v22/java-api/file/' },
            { label: '3.1.3 데이터베이스', link: '/v22/java-api/database/' },
            { label: '3.1.4 고수준 UI', link: '/v22/java-api/ui/' },
            { label: '3.1.5 Generic I/O', link: '/v22/java-api/generic-io/' },
            { label: '3.1.6 단말 리소스', link: '/v22/java-api/terminal-resource/' },
            { label: '3.1.7 매체 처리기', link: '/v22/java-api/media/' },
            { label: '3.1.8 SMS', link: '/v22/java-api/sms/' },
            { label: '3.1.9 부가 장치 제어', link: '/v22/java-api/device-control/' },
            { label: '4.1 확장 유니코드', link: '/v22/java-api/unicode/' },
          ],
        },
        {
          label: '선택 규격',
          collapsed: true,
          items: [
            { label: '선택 규격 개요', link: '/v22/optional/' },
            { label: '1. 동적 API', link: '/v22/optional/dynamic-api/' },
            { label: '2. VGI 관련 API', link: '/v22/optional/vgi/' },
          ],
        },
        {
          label: '부속서',
          collapsed: true,
          items: [
            { label: '부속서 개요', link: '/v22/appendix/' },
            { label: '1. API 혼용 기준', link: '/v22/appendix/api-interop/' },
            { label: '2. 보안 정책', link: '/v22/appendix/security-policy/' },
            { label: '3. ERROR 반환 값', link: '/v22/appendix/error-codes/' },
            { label: '4. 사용 예제', link: '/v22/appendix/examples/' },
            { label: '5. wCard', link: '/v22/appendix/wcard/' },
          ],
        },
      ],
    }),
  ],
});
